
x <- c(0,0,0,rep(1,100))
y <- filter(2*x+0.2*rnorm(length(x)),filter=0.9,method="recursive")
plot(y,xlim=c(0,40))
lines(x)
D <- data.frame(t=1:length(x), y=y, y.l1=lagVec(y,1), x=x)
fit <- lm(y ~ 0 + y.l1 + x,D)
summary(fit)
lines(c(NA,fit$fitted.values), col=2)
#acf(fit$residuals)
stepResponseARXNew(fit,D,"x","y",xlim=c(0,40))
stepResponseARX(fit,D,"x","y",xlim=c(0,40))

D2 <- resampleDF(D,Ts=3,startTime=1)
D2$y.l1 <- lagVec(D2$y,1)
fit2 <- lm(y ~ 0 + y.l1 + x,D2)
summary(fit2)
plot(D2$t,D2$y,xlim=c(0,40))
lines(D2$t,D2$x)
lines(D2$t,c(NA,fit2$fitted.values), col=2)
#acf(fit2$residuals)
#plot(fit2$residuals)
stepResponseARXNew(fit2,D2,"x","y",xlim=c(0,40))
